### PR TITLE
IGNITE-14376 Fixes exporting of discovery metrics via JMX.

### PR DESCRIPTION
**Pull request by ololo3000**
Thank you for submitting the pull request to the Apache Ignite.

In order to streamline the review of the contribution 
we ask you to ensure the following steps have been taken:

### The Contribution Checklist
- [ ] There is a single JIRA ticket related to the pull request. 
- [ ] The web-link to the pull request is attached to the JIRA ticket.
- [ ] The JIRA ticket has the _Patch Available_ state.
- [ ] The pull request body describes changes that have been made. 
The description explains _WHAT_ and _WHY_ was made instead of _HOW_.
- [ ] The pull request title is treated as the final commit message. 
The following pattern must be used: `IGNITE-XXXX Change summary` where `XXXX` - number of JIRA issue.
- [ ] A reviewer has been mentioned through the JIRA comments 
(see [the Maintainers list](https://cwiki.apache.org/confluence/display/IGNITE/How+to+Contribute#HowtoContribute-ReviewProcessandMaintainers)) 
- [ ] The pull request has been checked by the Teamcity Bot and 
the `green visa` attached to the JIRA ticket (see [TC.Bot: Check PR](https://mtcga.gridgain.com/prs.html))

### Notes
- [How to Contribute](https://cwiki.apache.org/confluence/display/IGNITE/How+to+Contribute)
- [Coding abbreviation rules](https://cwiki.apache.org/confluence/display/IGNITE/Abbreviation+Rules)
- [Coding Guidelines](https://cwiki.apache.org/confluence/display/IGNITE/Coding+Guidelines)
- [Apache Ignite Teamcity Bot](https://cwiki.apache.org/confluence/display/IGNITE/Apache+Ignite+Teamcity+Bot)

If you need any help, please email dev@ignite.apache.org or ask anу advice on http://asf.slack.com _#ignite_ channel.

### CODE REVIEW

**Review by NSAmelchev — COMMENTED** [review]
@ololo3000, Hi. I think the JMX exporter should be fixed. Other exporters process such metrics correctly.
Adding constraints and changing metric names should be done in a separate ticket. (Note that such change will change metric names in other exporters and can break user's monitoring systems) 

@nizhikov, Hi. What do you think about formalizing the name of metrics?
For now, only several TCP disco metrics differ from others as they name don't contain their metric registry name. (They created directly with MetricRegistry#register)

**Comment by nizhikov** [comment]
@NSAmelchev 

> What do you think about formalizing the name of metrics?

+1 for it.

>  such change will change metric names in other exporters and can break user's monitoring systems

specific metric names are not a part of public API.
I think we can fix it.

**Comment by nizhikov** [comment]
>  I think the JMX exporter should be fixed

+1 for that also.
It seems we should fix both - metric names and builtin exporter.

**Comment by dspavlov** [comment]
@ololo3000  was this change refused and PR #8937 applied instead?

**Comment by ololo3000** [comment]
@dspavlov  You are right. The issue related to this PR has been fixed by https://issues.apache.org/jira/browse/IGNITE-14428.

**Pull request closed without merging**
