### PR TITLE
IGNITE-5781 Visor throws ClassCastException if cache store implementa…

### PR DESCRIPTION
**Pull request by Desperus**
…tion is other than CacheJdbcPojoStore

### CODE REVIEW

**Comment by c0s** [comment]
This looks all right actually.

Could you please arrange a quick run of the tests on this fix on the official Ignite TeamCity server (http://ci.ignite.apache.org/queue.html)? Please be specifically aware about "http" protocol - the server isn't secured and if you're using anything like HTTPSEverywhere (as you should, of course) you won't be able to use the CI at all ;(

**Comment by Desperus** [comment]
Of course, here are test results: http://ci.ignite.apache.org/viewType.html?buildTypeId=IgniteTests_IgniteBasic&branch_IgniteTests=pull%2F2321%2Fhead&tab=buildTypeStatusDiv
New failed test does not seem connected to my changes.

**Comment by c0s** [comment]
Ah, great, I've missed it, I guess.
+1 for the fix. Will commit this by the end of the day!

**Comment by Desperus** [comment]
Hi @c0s . Just a reminder about this pull request. Thanks in advance.

**Comment by c0s** [comment]
The patch has been committed to the Ignite's master yesterday. The JIRA is resolved. You need to close your PR. Thanks for the contribution!

**Comment by Desperus** [comment]
Thank you.

**Pull request closed without merging**
