### PR TITLE
IGNITE-5332 Add toString() to GridNearAtomicAbstractSingleUpdateRequest and it's inheritors

### PR DESCRIPTION
**Pull request by Desperus**

### CODE REVIEW

**Comment by Desperus** [comment]
Hi @c0s . How is your progress?

**Comment by c0s** [comment]
Sorry, I was away. 

I have looked at this PR a bit more closely. The patch is good, but there some need to fix the commit message. It has to start with `IGNITE-5332' (note the capital letters).
The synopsis of the commit should match the JIRA name exactly. That allows apache jira bot to pick up the changes in the PR and populate them into the JIRA ticket. JIRA is (still) the main source of truth for all Apache projects. 
For more info, check this page https://cwiki.apache.org/confluence/display/IGNITE/How+to+Contribute#HowtoContribute-1.CreateGitHubpull-request and search for `To make contribution` section.

Looking forward for your fixes. Thank you!

**Comment by Desperus** [comment]
@c0s thanks for your feedback and sorry for the inconvenience. I've updated pull request by changing commit message.

**Comment by c0s** [comment]
Thanks! Could you please change the name of the PR so it gets associated with the JIRA ticket?

**Comment by Desperus** [comment]
Changed it as well.

**Comment by Desperus** [comment]
This ticket was implemented in master during implementation of  IGNITE-5473 (commit cf345b81820fbbcb82e5fcb2283b43ea286a40b4) so I'm closing this PR.

**Pull request closed without merging**
