### PR TITLE
IGNITE-14142 Document control.(sh|bin) command to get an arbitrary Sy…

### PR DESCRIPTION
**Pull request by Nikita-tech-writer**
…stemView

Thank you for submitting the pull request to the Apache Ignite.

In order to streamline the review of the contribution 
we ask you to ensure the following steps have been taken:

### The Contribution Checklist
- [ ] There is a single JIRA ticket related to the pull request. 
- [ ] The web-link to the pull request is attached to the JIRA ticket.
- [ ] The JIRA ticket has the _Patch Available_ state.
- [ ] The pull request body describes changes that have been made. 
The description explains _WHAT_ and _WHY_ was made instead of _HOW_.
- [ ] The pull request title is treated as the final commit message. 
The following pattern must be used: `IGNITE-XXXX Change summary` where `XXXX` - number of JIRA issue.
- [ ] A reviewer has been mentioned through the JIRA comments 
(see [the Maintainers list](https://cwiki.apache.org/confluence/display/IGNITE/How+to+Contribute#HowtoContribute-ReviewProcessandMaintainers)) 
- [ ] The pull request has been checked by the Teamcity Bot and 
the `green visa` attached to the JIRA ticket (see [TC.Bot: Check PR](https://mtcga.gridgain.com/prs.html))

### Notes
- [How to Contribute](https://cwiki.apache.org/confluence/display/IGNITE/How+to+Contribute)
- [Coding abbreviation rules](https://cwiki.apache.org/confluence/display/IGNITE/Abbreviation+Rules)
- [Coding Guidelines](https://cwiki.apache.org/confluence/display/IGNITE/Coding+Guidelines)
- [Apache Ignite Teamcity Bot](https://cwiki.apache.org/confluence/display/IGNITE/Apache+Ignite+Teamcity+Bot)

If you need any help, please email dev@ignite.apache.org or ask anу advice on http://asf.slack.com _#ignite_ channel.

### CODE REVIEW

**Comment by Nikita-tech-writer** [comment]
@ololo3000 Please have a look a the PR.

**Comment by ololo3000** [comment]
@Nikita-tech-writer Merge the master branch into your branch, please. And, please, take a look at PR [1]. It also provides some documentation for system-view command (discussion - [2]).

[1] - https://github.com/apache/ignite/pull/8630/files
[2] - http://apache-ignite-developers.2346864.n4.nabble.com/DISCUSSION-Apache-Ignite-Release-2-10-time-scope-manager-tp50037p50954.html

**Comment by Nikita-tech-writer** [comment]
@ololo3000 Thank you very much for letting me know about the already prepared documentation (totally missed that!). 
In this respect, I do believe that we can close my PR, as I have no objections regarding your version (moreover, it includes more detailed information). Thanks once again!

**Comment by Mmuzaf** [comment]
@Nikita-tech-writer @ololo3000 

Thank guys, so I've closed the issue.

**Pull request closed without merging**
