### PR TITLE
IGNITE-12723: getMXBean for tests introduced.

### PR DESCRIPTION
**Pull request by nizhikov**

### CODE REVIEW

**Comment by Vladsz83** [comment]
@nizhikov , 

1) Should we slightly rename `GridAbstractTest#metricRegistry()`?

2) Do we need to keep `CacheMetricsManageTest#mxBean()` `ClusterBaselineNodesMetricsSelfTest#mxBean()`, `GridCacheLongRunningTransactionDiagnosticsTest#txMXBean()`, `SetTxTimeoutOnPartitionMapExchangeTest#txMXBean()`, `TcpCommunicationStatisticsTest#mbean()`? Why not using `GridAbstractTest#getMxBean()` directly?

**Comment by nizhikov** [comment]
@Vladsz83 Thanks for the review

> Should we slightly rename GridAbstractTest#metricRegistry()?

Rename of the existing methods is not the goal of this ticket.
What name is more convenient?

> Do we need to keep

Yes. These methods used multiple times, so I think it OK to keep them.

**Comment by Vladsz83** [comment]
@nizhikov , 
>>> What name is more convenient?

I was confused with 'metric registry' and dynamic mbeans, dynamic mbean creation. The method is about dynamic mbean to show some numbers, but not exactly for a metric registry . Better name might be ‘metricMXBean’

**Comment by nizhikov** [comment]
> Better name might be ‘metricMXBean’

Got it. Thank you.

**Pull request merged**
