### PR TITLE
Docker image for Ignite 1.6.0

### PR DESCRIPTION
**Pull request by zshamrock**

### CODE REVIEW

**Comment by zshamrock** [comment]
@lftrevisan I've updated the Dockerfile following the Best Practices https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/.

The resulting size was reduced from 1.061 GB to 885 MB.

Also output from `docker history apacheignite/ignite:1.6.0`:

IMAGE               CREATED             CREATED BY                                      SIZE                COMMENT
b80d86b4ec2f        45 minutes ago      /bin/sh -c #(nop) CMD ["/bin/sh" "-c" "$IGNIT   0 B                 
3aaeaee0fd1b        54 minutes ago      /bin/sh -c chmod +x $IGNITE_HOME/run.sh         1.36 kB             
7a8a513aaa9a        54 minutes ago      /bin/sh -c #(nop) COPY file:ff3878065a272efc7   1.36 kB             
75938738b292        54 minutes ago      /bin/sh -c curl http://www.us.apache.org/dist   242.1 MB            
9232622cc809        56 minutes ago      /bin/sh -c #(nop) WORKDIR /opt/ignite           0 B                 
8e8110891553        56 minutes ago      /bin/sh -c apt-get update && apt-get install    0 B                 
479e12f83587        56 minutes ago      /bin/sh -c #(nop) ENV IGNITE_HOME=/opt/ignite   0 B                 
78f665490591        56 minutes ago      /bin/sh -c #(nop) ENV IGNITE_VERSION=1.6.0      0 B                 
713a9aa340eb        12 days ago         /bin/sh -c /var/lib/dpkg/info/ca-certificates   418.2 kB            
<missing>           12 days ago         /bin/sh -c set -x  && apt-get update  && apt-   349.2 MB            
<missing>           12 days ago         /bin/sh -c #(nop) ENV CA_CERTIFICATES_JAVA_VE   0 B                 
<missing>           12 days ago         /bin/sh -c #(nop) ENV JAVA_DEBIAN_VERSION=8u9   0 B                 
<missing>           12 days ago         /bin/sh -c #(nop) ENV JAVA_VERSION=8u91         0 B                 
<missing>           12 days ago         /bin/sh -c #(nop) ENV JAVA_HOME=/usr/lib/jvm/   0 B                 
<missing>           12 days ago         /bin/sh -c {   echo '#!/bin/sh';   echo 'set    87 B                
<missing>           12 days ago         /bin/sh -c #(nop) ENV LANG=C.UTF-8              0 B                 
<missing>           12 days ago         /bin/sh -c echo 'deb http://httpredir.debian.   61 B                
<missing>           12 days ago         /bin/sh -c apt-get update && apt-get install    1.285 MB            
<missing>           12 days ago         /bin/sh -c apt-get update && apt-get install    122.6 MB            
<missing>           12 days ago         /bin/sh -c apt-get update && apt-get install    44.3 MB             
<missing>           12 days ago         /bin/sh -c #(nop) CMD ["/bin/bash"]             0 B                 
<missing>           12 days ago         /bin/sh -c #(nop) ADD file:5d8521419ad6cfb695   125.1 MB

**Comment by lftrevisan** [comment]
Nice job. Is it possible to use a jre base image instead of the jdk version?

**Comment by zshamrock** [comment]
Using JRE base image should be fine, unless someone from Apache Ignite developers know the reason why the full JDK is required (to support zero deployment? or JRE would be sufficient as well?). 

At least the official Getting Started doc says "Apache Ignite was officially tested on: Oracle JDK 7 and above". So the docker image is already based on non-tested open JDK, so maybe better stay with it, at least some guarantee.

**Comment by zshamrock** [comment]
Any progress on this one?

**Pull request closed without merging**
