### PR TITLE
IGNITE-23820 Restore 'checkout' in `sonar-pr-from-fork-build.yml`

### PR DESCRIPTION
**Pull request by raboof**
Follow-up on 964dc48 which removed the checkout from the pull-request workflow entirely. This should now check out the default rev (which should be the code from the PR as it was when the workflow was approved).

Thank you for submitting the pull request to the Apache Ignite.

In order to streamline the review of the contribution 
we ask you to ensure the following steps have been taken:

### The Contribution Checklist
- [ ] There is a single JIRA ticket related to the pull request. 
- [ ] The web-link to the pull request is attached to the JIRA ticket.
- [ ] The JIRA ticket has the _Patch Available_ state.
- [ ] The pull request body describes changes that have been made. 
The description explains _WHAT_ and _WHY_ was made instead of _HOW_.
- [ ] The pull request title is treated as the final commit message. 
The following pattern must be used: `IGNITE-XXXX Change summary` where `XXXX` - number of JIRA issue.
- [ ] A reviewer has been mentioned through the JIRA comments 
(see [the Maintainers list](https://cwiki.apache.org/confluence/display/IGNITE/How+to+Contribute#HowtoContribute-ReviewProcessandMaintainers)) 
- [ ] The pull request has been checked by the Teamcity Bot and 
the `green visa` attached to the JIRA ticket (see [TC.Bot: Check PR](https://mtcga.gridgain.com/prs.html))

### Notes
- [How to Contribute](https://cwiki.apache.org/confluence/display/IGNITE/How+to+Contribute)
- [Coding abbreviation rules](https://cwiki.apache.org/confluence/display/IGNITE/Abbreviation+Rules)
- [Coding Guidelines](https://cwiki.apache.org/confluence/display/IGNITE/Coding+Guidelines)
- [Apache Ignite Teamcity Bot](https://cwiki.apache.org/confluence/display/IGNITE/Apache+Ignite+Teamcity+Bot)

If you need any help, please email dev@ignite.apache.org or ask anу advice on http://asf.slack.com _#ignite_ channel.

### CODE REVIEW

**Comment by skorotkov** [comment]
Hi Arnout Engelen,

Thanks!

Now it does the build.

But we still need to return back the fetch of the PR's base branch (which is master in fact) from the upstream (main ignite) repo. Otherwise the Sonar would fail to detect the "new lines of code" if  fork's master is not synchronized with main repo.

See details at  https://community.sonarsource.com/t/how-to-use-sonarcloud-with-a-forked-repository-on-github/7363/32

Do you see any security risks in fetching of the master branch from the main ignite repo?

**Comment by raboof** [comment]
I think that should be OK, as we trust `$pr_base_ref` (because it should have been reviewed). Hardcoding `${{ github.event.repository.clone_url }}` and `${{ github.event.workflow_run.head_branch }}` (as `-`) might be nice just to reduce attack surface - I guess perhaps we could even hard-code `$pr_base_ref` (as `master`)?

**Comment by skorotkov** [comment]
Yes we may  hardcode the `${{ github.event.repository.clone_url }}`  and 
replace `${{ github.event.workflow_run.head_branch }}` with `github.event.workflow_run.head_sha`.  `-` also may  work but should be tested.

As far as the `$pr_base_ref`. I wouldn't  hardcode it.  Sometimes mainteners want to do PRs to some non-master branch which accumulates changes for some big feature.  See the recent example  https://github.com/apache/ignite/pull/11618

**Review by skorotkov — APPROVED** [review]
Look good for me now

**Pull request merged**
