### PR TITLE
IGNITE-18830 Optimize log in GridQueryProcessor

### PR DESCRIPTION
**Pull request by Shoothzj**
Thank you for submitting the pull request to the Apache Ignite.

In order to streamline the review of the contribution 
we ask you to ensure the following steps have been taken:

### The Contribution Checklist
- [x] There is a single JIRA ticket related to the pull request. 
- [ ] The web-link to the pull request is attached to the JIRA ticket.
- [ ] The JIRA ticket has the _Patch Available_ state.
- [ ] The pull request body describes changes that have been made. 
The description explains _WHAT_ and _WHY_ was made instead of _HOW_.
- [x] The pull request title is treated as the final commit message. 
The following pattern must be used: `IGNITE-XXXX Change summary` where `XXXX` - number of JIRA issue.
- [ ] A reviewer has been mentioned through the JIRA comments 
(see [the Maintainers list](https://cwiki.apache.org/confluence/display/IGNITE/How+to+Contribute#HowtoContribute-ReviewProcessandMaintainers)) 
- [ ] The pull request has been checked by the Teamcity Bot and 
the `green visa` attached to the JIRA ticket (see [TC.Bot: Check PR](https://mtcga.gridgain.com/prs.html))

### CODE REVIEW

**Comment by Shoothzj** [comment]
@petrov-mg Could you please take a look?

**Comment by Shoothzj** [comment]
@petrov-mg Thanks for your attention. I have fixed that, PTAL again. Thanks :)

**Comment by Shoothzj** [comment]
@petrov-mg Could you please take a look again?

**Comment by Shoothzj** [comment]
@ivandasch could you please take a look? thanks

**Comment by Shoothzj** [comment]
@petrov-mg @ivandasch PTAL, thanks :)

**Comment by Shoothzj** [comment]
@petrov-mg @ivandasch PTAL, thanks :)

**Comment by Shoothzj** [comment]
@petrov-mg @ivandasch PTAL, thanks :)

**Comment by Shoothzj** [comment]
@sk0x50 PTAL, thanks

**Comment by Shoothzj** [comment]
@petrov-mg @ivan-fedorenkov @sk0x50 PTAL, thanks :)

**Comment by Shoothzj** [comment]
@petrov-mg @ivan-fedorenkov @sk0x50 PTAL  when you have time, thanks in advance. :)

**Comment by Shoothzj** [comment]
@petrov-mg @ivan-fedorenkov @sk0x50 PTAL  when you have time, thanks in advance. :)

**Comment by Shoothzj** [comment]
@ptupitsyn @petrov-mg @ivan-fedorenkov @sk0x50 PTAL  when you have time, thanks in advance. :)

**Comment by Shoothzj** [comment]
@ptupitsyn @petrov-mg @ivan-fedorenkov @sk0x50 PTAL  when you have time, thanks in advance. :)

**Comment by Shoothzj** [comment]
@ptupitsyn @petrov-mg @ivan-fedorenkov @sk0x50 PTAL , thanks in advance. :)

**Review by petrov-mg — APPROVED** [review]

**Pull request merged**
